---
- name: Setup SOCKS5 server using microsocks
  hosts: all
  vars_files:
    - ./secrets.yml
  become: true
  tasks:
    - name: Ensure essential packages are present
      ansible.builtin.import_tasks: tasks/install_packages.yml
    - name: Ensure microsocks is present and working
      ansible.builtin.import_tasks: tasks/socks.yml
