---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
- name: Install Git and GCC toolchain
  ansible.builtin.package:
    name:
      - git
      - build-essential
    state: present
- name: Check if microsocks already built
  ansible.builtin.stat:
    path: '/usr/local/bin/microsocks'
  register: microsocks
- name: Building microsocks block
  when: not microsocks.stat.exists
  block:
    - name: Git clone microsocks
      ansible.builtin.git:
        repo: 'https://github.com/rofl0r/microsocks'
        dest: /usr/local/src/microsocks
        version: master
    - name: Make from source
      community.general.make:
        chdir: /usr/local/src/microsocks
        target: install
- name: Check if microsocks systemd service present
  ansible.builtin.stat:
    path: '/etc/systemd/system/microsocks.service'
  register: microsocks_systemd
- name: Managing microsocks systemd service block
  when: not microsocks_systemd.stat.exists
  block:
    - name: Generate the systemd microsocks service file
      ansible.builtin.template:
        src: microsocks.service.j2
        dest: /etc/systemd/system/microsocks.service
        mode: '0644'
    - name: Enable and start the microsocks service
      ansible.builtin.systemd:
        name: microsocks
        enabled: true
        state: started
